// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIeHfa9hs3xw3ye_zg7fYs91z-3RZfuM',
    appId: '1:411324226230:web:2f05365d182a9cbeff6417',
    messagingSenderId: '411324226230',
    projectId: 'private-sojuz',
    authDomain: 'private-sojuz.firebaseapp.com',
    storageBucket: 'private-sojuz.firebasestorage.app',
    measurementId: 'G-KRR4JKR6YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcY_cIT-HAm6X4s-qSipRVrPtqj-guWo',
    appId: '1:411324226230:android:5390c3e06673d645ff6417',
    messagingSenderId: '411324226230',
    projectId: 'private-sojuz',
    storageBucket: 'private-sojuz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbYMwnGUfwJWobb8B_Bfk-WKgScB-QqxQ',
    appId: '1:411324226230:ios:b995f83358a3690aff6417',
    messagingSenderId: '411324226230',
    projectId: 'private-sojuz',
    storageBucket: 'private-sojuz.firebasestorage.app',
    iosBundleId: 'com.example.devPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbYMwnGUfwJWobb8B_Bfk-WKgScB-QqxQ',
    appId: '1:411324226230:ios:b995f83358a3690aff6417',
    messagingSenderId: '411324226230',
    projectId: 'private-sojuz',
    storageBucket: 'private-sojuz.firebasestorage.app',
    iosBundleId: 'com.example.devPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALIeHfa9hs3xw3ye_zg7fYs91z-3RZfuM',
    appId: '1:411324226230:web:b16c53f620973820ff6417',
    messagingSenderId: '411324226230',
    projectId: 'private-sojuz',
    authDomain: 'private-sojuz.firebaseapp.com',
    storageBucket: 'private-sojuz.firebasestorage.app',
    measurementId: 'G-6R5RS3TRCG',
  );
}